name: BuildProject

on: [push]

jobs:
  BuildOnWindows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
  
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build
      run: msbuild /p:Configuration=Release -restore

  BuildOnLinux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: RestoreWorkload
      run: dotnet workload restore UnoSpySnoop/UI/UnoSpySnoopDebugger.Skia.Gtk/UnoSpySnoopDebugger.Skia.Gtk.csproj
    - name: RestoreGtk
      run: dotnet restore -p:TargetFramework=net8.0 -r linux-x64 UnoSpySnoop/UI/UnoSpySnoopDebugger.Skia.Gtk/UnoSpySnoopDebugger.Skia.Gtk.csproj
    - name: BuildGtk
      run: dotnet build -c release -r linux-x64 -p:TargetFramework=net8.0 --no-restore UnoSpySnoop/UI/UnoSpySnoopDebugger.Skia.Gtk/UnoSpySnoopDebugger.Skia.Gtk.csproj
    - name: RestoreFrameBuffer
      run: dotnet restore -p:TargetFramework=net8.0 -r linux-x64 UnoSpySnoop/UI/UnoSpySnoopDebugger.Skia.Linux.FrameBuffer/UnoSpySnoopDebugger.Skia.Linux.FrameBuffer.csproj
    - name: BuildFrameBuffer
      run: dotnet build -c release -r linux-x64 -p:TargetFramework=net8.0 --no-restore UnoSpySnoop/UI/UnoSpySnoopDebugger.Skia.Linux.FrameBuffer/UnoSpySnoopDebugger.Skia.Linux.FrameBuffer.csproj

  BuildOnMac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Restore
      run: dotnet workload restore UnoSpySnoop/UI/UnoSpySnoopDebugger.Skia.Gtk/UnoSpySnoopDebugger.Skia.Gtk.csproj
    - name: BuildGtk
      run: dotnet build UnoSpySnoop/UI/UnoSpySnoopDebugger.Skia.Gtk/UnoSpySnoopDebugger.Skia.Gtk.csproj
